<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdac4b884752515a6658a5dbc241ac3aa
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WechatPay\\GuzzleMiddleware\\' => 27,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WechatPay\\GuzzleMiddleware\\' => 
        array (
            0 => __DIR__ . '/..' . '/wechatpay/wechatpay-guzzle-middleware/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitdac4b884752515a6658a5dbc241ac3aa::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitdac4b884752515a6658a5dbc241ac3aa::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitdac4b884752515a6658a5dbc241ac3aa::$classMap;

        }, null, ClassLoader::class);
    }
}
